lb_name: sqllb3
rg_name: sqllb
bep_name: backend
default_fip_name: deletelater
sku_value: Standard
subnet_name: default
vnet_name: vnet1
frontend_name: frontend
private_ip_addr: 10.0.0.17
availability_zone: 1 2 3
probe_name: lb_hp
probe_port: 59999
protocol: Tcp
interval_value: 5
rule_name: lb_rule
frontend_port: 1899
backend_port: 1899
load_distribution: SourceIPProtocol
tcp_reset: no
floating_ip: yes
