---
   - name: Create and Configure Frontend IP
     block:
     - name: Create and Configure frontend IP
       shell: "az network lb frontend-ip create --lb-name {{ lb_name }}
                                                --resource-group {{ rg_name }}
                                                --name {{ frontend_name }}
                                                --private-ip-address {{ private_ip_addr }}
                                                --zone {{ availability_zone }}
                                                --vnet-name {{ vnet_name }}
                                                --subnet {{ subnet_name }} "
       register: create_fip_status

     - name: Check the status of Frontend ip creation
       debug:
         msg: "Front End IP creation and configuration completed successfully"
       when: create_fip_status.rc == 0

     - name: Delete the deafult frontend IP created
       shell: "az network lb frontend-ip delete --lb-name {{ lb_name }}
                                                --resource-group {{ rg_name }}
                                                --name {{ default_fip_name }}"
       register: delete_default_fip_status

     - name: Check the status of default frontemd ip deletion
       debug:
         msg: "Default frontend IP deleted successfully"
       when: delete_default_fip_status.rc == 0

     rescue:
     - fail: 
        msg: "Error occured while creating and configuring frontend ip"


