---
- name: Check the load balancer name exist
  block:
  - name: Fetch load balancer name
    shell: "az network lb list --resource-group {{rg_name}} --query \"[?name=='{{ lb_name }}'] | length(@)\""
    register: check_lb_exist

  - name: Check if load balancer name already in use
    debug:
      msg: "Load balancer name {{ lb_name }} already exist so kindly check"
    when: check_lb_exist.stdout > "0"

  rescue:
  - fail:
     msg: "Error while fetching the load balancer details"
