---
- name: Create and Configure Frontend IP
  block:
  - name: Create and Configure frontend IP
    shell: "az network lb frontend-ip create --lb-name {{ lb_name }}
            --resource-group {{ rg_name }}
            --name {{ frontend_name }}
            --private-ip-address {{ private_ip_addr }}
            --zone {{ availability_zone }}
            --vnet-name {{ vnet_name }}
            --subnet {{ subnet_name }}"
    register: create_fip_status
 
  - name: Print Frontend IP created message
    debug:
      msg: "Azure Internal Load Balncer Front End IP creation and configuration completed successfully"
    when: create_fip_status.rc == 0

  - name: Print Frontend IP not created message
    debug:
      msg: "Azure Internal Load Balncer Front End IP creation and configuration was unsuccesful"
    when: create_fip_status.rc != 0

  - name: Delete the deafult frontend IP created
    shell: "az network lb frontend-ip delete --lb-name {{ lb_name }}
            --resource-group {{ rg_name }}
            --name {{ default_fip_name }}"
    register: delete_default_fip_status
    when: "'Not-Exist' in get_lb_name.stdout"
 
  - name: Print default Frontend IP deleted message
    debug:
      msg: "Azure load balancer default frontend IP deleted successfully"
    when: delete_default_fip_status.changed

  - name: Print default Frontend IP not deleted message
    debug:
      msg: "Azure load balancer default frontend IP was not found because its existing frontend"
    when: delete_default_fip_status.skipped

  rescue:
  - fail: 
     msg: "Error occured while executing Azure CLI command"


