---
- name: Create and Configure Frontend IP
  block:
  - name: Create and Configure load balancer frontend IP
    shell: "az network lb frontend-ip create --lb-name {{ lb_name }}
            --resource-group {{ rg_name }}
            --name {{ frontend_name }}
            --private-ip-address {{ private_ip_addr }}
            --zone {{ availability_zone }}
            --vnet-name {{ vnet_name }}
            --subnet {{ subnet_name }}"
    register: create_fip_status
 
  - name: Check if load balancer frontend IP created
    debug:
      msg: "{% if create_fip_status.rc == 0 %} Load balancer frontend IP creation and configuration completed successfully \ 
            {% else %} Load balncer frontend IP creation and configuration was unsuccesful {% endif %}"
 
  - name: Delete the deafult frontend IP
    shell: "az network lb frontend-ip delete 
            --lb-name {{ lb_name }}
            --resource-group {{ rg_name }}
            --name {{ default_fip_name }}"
    register: delete_default_fip_status
    when: "'Not-Exist' in get_lb_name.stdout"
 
  - name: Check default frontend IP deleted or not
    debug:
      msg: "{% if delete_default_fip_status.changed %} Load balancer default frontend IP deleted successfully \
            {% else %} Load balancer default frontend IP was not found because its existing frontend {% endif %}"

  rescue:
  - fail: 
     msg: "Error while executing create frontend IP Azure CLI command"


