---
- name: Create backend pool
  block:
  - name: Configure load balancer backend pool
    shell: "az network lb address-pool address add 
            --resource-group {{ rg_name }}
            --lb-name {{ lb_name }}
            --pool-name {{ bep_name }}
            --name {{ item.addr }}
            --vnet {{ vnet_name }}
            --ip-address {{ item.ip }}"
    register: create_bep_status
    with_items: "{{ backendips }}"

  - name: Print configure backend pool message
    debug:
      msg: "load balancer backend pool configured successfully"
    when: create_bep_status.results[0].rc == 0 and create_bep_status.results[1].rc == 0
  
  rescue:
  - fail: 
     msg: "Error occured while executing Azure CLI command"


