---
- name: Check the Virtual Network
  block:
  - name: Check if vnet exist
    shell: "if {{ fetch_vnet_info }} >> /dev/null; then echo 'Exist'; else echo 'Not-Exist'; fi;"
    register: get_vnet_name
    #when: "'Exist' == get_rg_name.stdout"
    changed_when: false

  - name: Print message if vnet exist
    debug:
      msg: "The virtual network : {{ vnet_name }} found in resource group: {{ rg_name }}"
    when: "'Exist' == get_vnet_name.stdout"

  - name: Fail if vnet not exist
    fail:
     msg: "The Virual Network : {{ vnet_name }} not found,so exiting the playbook"
    when: "'Not-Exist' == get_vnet_name.stdout"

  rescue:
  - fail:
     msg: "Error while executing check vnet exist Azure CLI command"
