---
- name: Check Subnet
  block:
  - name: Check if subnet exist
    shell: "if {{ fetch_subnet_info }} >> /dev/null; then echo 'Exist'; else echo 'Not-Exist'; fi;"
    register: get_subnet_name
    #when: "'Exist' == get_vnet_name.stdout and 'Exist' == get_rg_name.stdout"
    changed_when: false

  - name: Print message if subnet exist
    debug:
      msg: "The subnet: {{ subnet_name }} found in resource group: {{ rg_name }} and VNet: {{ vnet_name }}"
    when: "'Exist' == get_subnet_name.stdout"

  - name: Fail if subnet not exist
    fail:
     msg: "The subnet: {{ subnet_name }} not found, so exiting the playbook"
    when: "'Not-Exist' == get_subnet_name.stdout"

  rescue:
  - fail:
     msg: "Error while executing check subnet exist Azure CLI command"
