---
- name: Check load balancer
  block:
  - name: Get load balancer name
    shell: "if {{ fetch_lb_info }} >> /dev/null; then echo 'Exist'; else echo 'Not-Exist'; fi;"
    register: get_lb_name
    #when: "'Exist' == get_rg_name.stdout and 'Exist' == get_vnet_name.stdout"
    changed_when: false

  - name: Check if load balancer exist
    debug:
      msg: "{% if get_lb_name.stdout == 'Exist' %} The load balancer: {{ lb_name }} already exist under resource group: {{ rg_name }}, \
            vnet/subnet: {{ vnet_name }}/{{subnet_name}} so it will be updated {% else %} The load balancer: {{ lb_name }} not found, \
            so new load balancer will be created under resource group: {{ rg_name }}, vnet/subnet: {{ vnet_name }}/{{subnet_name}} \
            {% endif %}"
 
  rescue:
  - fail:
     msg: "Error while executing check load balancer exist Azure CLI command"
